from enum import Enum

class State(str, Enum):
    IDLE = "IDLE"
    UPLOAD_SYLLABUS = "UPLOAD_SYLLABUS"
    PROCESS_SYLLABUS = "PROCESS_SYLLABUS"
    COMPARE_CURRICULUM = "COMPARE_CURRICULUM"
    IDENTIFY_GAPS = "IDENTIFY_GAPS"
    GENERATE_REPORT = "GENERATE_REPORT"
    COMPLETED = "COMPLETED"
